# packages in addition to repo2docker/buildpacks/conda/environment.yml
name: notebook
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - jupyterhub
  - jupyter-server-proxy
  - nbgitpuller
  - dask
  - distributed
  - dask-labextension
  - tornado
  - bokeh
  - python-graphviz
  - pip
  - python=3.9
  - scipy
  - scikit-image
  - numpy=1.23.5
  - pandas
  - matplotlib
  - astropy
  - beautifulsoup4
  - bokeh
  - bzip2 
  - cairo 
  - cartopy
  - jupyterlab 
  - ipympl
  - wget 
  - requests
  - urllib3
  - xmltodict
  
 # geospatial (raster+vector)
  - gdal
  - rasterio
  - geopandas
  - pygeos
  - shapely
  - contextily
  - descartes
  - affine
  - earthaccess
  - xdem
  - arosics
  - pip
  - psutil
  - pip:
    - geojson
    - matplotlib-colorbar
    - matplotlib-scalebar
    - multiprocess
    - p-tqdm
    - ppft
    - chardet
    # geospatial+plotting
    - "--editable=git+https://github.com/dshean/pygeotools.git#egg=pygeotools"
    - "--editable=git+https://github.com/dshean/demcoreg.git#egg=demcoreg"
    - "--editable=git+https://github.com/ShashankBice/imview.git@jglac#egg=imview"
    - "--editable=git+https://github.com/ShashankBice/debris_cover_smb.git#egg=debris_cover_smb"

