# packages in addition to repo2docker/buildpacks/conda/environment.yml
name: notebook
channels:
  - conda-forge
dependencies:
  - jupyterlab=1.2
  - jupyterhub=1.0
  - jupyter-server-proxy=1.1
  - nbgitpuller=0.7
  - dask=2.8
  - distributed=2.8
  - dask-labextension=1.0
  - tornado=6.0
  - bokeh=1.4
  - python-graphviz=0.13
  - pip
  - python=3.9
  - scipy
  - scikit-image
  - numpy
  - pandas
  - matplotlib
  - astropy
  - beautifulsoup4
  - bokeh
  - bzip2 
  - cairo 
  - cartopy
  - jupyterlab 
  - ipympl
  - wget 
  - requests
  - urllib3
  - xmltodict
  
 # geospatial (raster+vector)
  - gdal
  - rasterio
  - geopandas
  - pygeos
  - shapely
  - contextily
  - descartes
  - affine
  - earthaccess
  - xdem
  - arosics
  - pip
  - psutil
  - pip:
    - geojson
    - matplotlib-colorbar
    - matplotlib-scalebar
    - multiprocess
    - p-tqdm
    - ppft
    - chardet
    # geospatial+plotting
    - "--editable=git+https://github.com/dshean/pygeotools.git#egg=pygeotools"
    - "--editable=git+https://github.com/dshean/demcoreg.git#egg=demcoreg"
    - "--editable=git+https://github.com/ShashankBice/imview.git@jglac#egg=imview"
    - "--editable=git+https://github.com/ShashankBice/debris_cover_smb.git#egg=debris_cover_smb"

